# Generated by Django 6.0.4 on 2026-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='yапишите название блга')),
                ('description', models.TextField(blank=True, verbose_name='напишите статью')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='загрузите фото')),
                ('blog_file', models.FileField(upload_to='blog/', verbose_name='загрузите пдф файл')),
                ('type_blog', models.CharField(choices=[('програмирование', 'pпрограмирование'), ('бизнес', 'бизнес'), ('медецина', 'медецина')], default='програмирование', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
