# Generated by Django 6.0.4 on 2026-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Обложка')),
                ('book_file', models.FileField(upload_to='book_files/', verbose_name='Файл книги')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('publisher', models.CharField(max_length=255, verbose_name='Издательство')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
